"""Build the SQLite database, run validated queries, and summarise the answers.

Rebuild the database with::

    python -m src.talk_to_data.query_runner --rebuild

Ask a question end to end with::

    python -m src.talk_to_data.query_runner --ask "How many applicants defaulted?"
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np
import pandas as pd

from src.data.preprocessor import RETIREE_FLAG, RETIREE_PLACEHOLDER
from src.talk_to_data.nl_to_sql import check_sql_safety, complete, nl_to_sql
from src.talk_to_data.prompt_templates import (
    COLUMN_DESCRIPTIONS,
    SUMMARY_SYSTEM_PROMPT,
    TABLE_NAME,
    build_summary_user_prompt,
)
from src.utils.config import DB_PATH, PROJECT_ROOT
from src.utils.logger import get_logger

logger = get_logger(__name__)

SCHEMA_PATH = PROJECT_ROOT / "sql" / "schema.sql"
MAX_RESULT_ROWS = 1000
SUMMARY_ROW_LIMIT = 50

SQLITE_TYPES = {
    "int64": "INTEGER",
    "int32": "INTEGER",
    "int8": "INTEGER",
    "float64": "REAL",
    "float32": "REAL",
    "bool": "INTEGER",
}
INDEXED_COLUMNS = [
    "TARGET",
    "risk_band",
    "NAME_EDUCATION_TYPE",
    "age_bracket",
    "NAME_INCOME_TYPE",
]


@dataclass
class QueryResult:
    """Outcome of running one SQL statement."""

    ok: bool
    sql: str
    dataframe: pd.DataFrame | None = None
    error: str = ""
    row_count: int = 0
    truncated: bool = False


@dataclass
class Answer:
    """A question carried through generation, execution, and summarisation."""

    question: str
    sql: str = ""
    result: QueryResult | None = None
    answer: str = ""
    errors: list[str] = field(default_factory=list)


# --------------------------------------------------------------- build the db


def build_applicants_frame() -> pd.DataFrame:
    """Denormalised one-row-per-applicant frame, including model scores."""
    from src.data.loader import build_master_dataset
    from src.ml.predict import load_model_artifacts, risk_band

    master = build_master_dataset()
    frame = master.copy()

    # Bracket from the unrounded age so the bands match notebooks/eda.py exactly;
    # rounding first pushes applicants just under a boundary into the next band.
    exact_age = -frame["DAYS_BIRTH"] / 365.25
    frame["age_years"] = exact_age.round(2)
    frame["age_bracket"] = pd.cut(
        exact_age,
        bins=[20, 30, 40, 50, 60, 120],
        labels=["20-29", "30-39", "40-49", "50-59", "60+"],
        right=False,
    ).astype("object")

    placeholder = frame["DAYS_EMPLOYED"].eq(RETIREE_PLACEHOLDER)
    frame[RETIREE_FLAG] = placeholder.astype("int8")
    frame["years_employed"] = (
        -frame["DAYS_EMPLOYED"].mask(placeholder) / 365.25
    ).round(2)

    income = frame["AMT_INCOME_TOTAL"].where(frame["AMT_INCOME_TOTAL"] > 0)
    frame["credit_to_income"] = (frame["AMT_CREDIT"] / income).round(4)
    frame["annuity_to_income"] = (frame["AMT_ANNUITY"] / income).round(4)
    frame["income_quartile"] = pd.qcut(
        frame["AMT_INCOME_TOTAL"],
        4,
        labels=["Q1 (lowest)", "Q2", "Q3", "Q4 (highest)"],
    ).astype("object")

    logger.info("Scoring every applicant with the trained model...")
    artifacts = load_model_artifacts()
    features = artifacts.preprocessor.transform(master).to_numpy(dtype="float32")
    probabilities = artifacts.model.predict_proba(features)[:, 1]
    frame["default_probability"] = probabilities.round(6)
    frame["risk_band"] = [risk_band(float(value)) for value in probabilities]

    return frame


def generate_schema_sql(frame: pd.DataFrame) -> str:
    """Emit CREATE TABLE DDL mirroring the frame, annotated with descriptions."""
    lines = [
        "-- Generated by src/talk_to_data/query_runner.py (--rebuild).",
        "-- One denormalised row per loan applicant, mirroring the master dataset",
        "-- plus derived helper columns and the trained model's score.",
        "",
        f"DROP TABLE IF EXISTS {TABLE_NAME};",
        "",
        f"CREATE TABLE {TABLE_NAME} (",
    ]

    definitions = []
    for column in frame.columns:
        sql_type = SQLITE_TYPES.get(str(frame[column].dtype), "TEXT")
        if column == "SK_ID_CURR":
            definition = f"    {column} INTEGER PRIMARY KEY"
        else:
            definition = f"    {column} {sql_type}"
        description = COLUMN_DESCRIPTIONS.get(column)
        definitions.append((definition, description))

    width = max(len(definition) for definition, _ in definitions)
    for index, (definition, description) in enumerate(definitions):
        comma = "," if index < len(definitions) - 1 else ""
        row = f"{definition}{comma}"
        if description:
            row = f"{row.ljust(width + 1)}  -- {description}"
        lines.append(row)

    lines.append(");")
    lines.append("")
    for column in INDEXED_COLUMNS:
        if column in frame.columns:
            lines.append(
                f"CREATE INDEX idx_{TABLE_NAME}_{column.lower()} "
                f"ON {TABLE_NAME}({column});"
            )
    lines.append("")
    return "\n".join(lines)


def build_database(db_path: Path | None = None, chunksize: int = 10_000) -> Path:
    """Rebuild sql/schema.sql and load the applicants table into SQLite."""
    path = Path(db_path or DB_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)

    frame = build_applicants_frame()

    SCHEMA_PATH.parent.mkdir(parents=True, exist_ok=True)
    schema = generate_schema_sql(frame)
    SCHEMA_PATH.write_text(schema, encoding="utf-8")
    logger.info("Wrote %s (%d columns)", SCHEMA_PATH.relative_to(PROJECT_ROOT), len(frame.columns))

    # Object columns may hold numpy scalars that sqlite3 cannot bind directly.
    frame = frame.replace({np.nan: None})

    with sqlite3.connect(path) as connection:
        connection.executescript(schema)
        frame.to_sql(
            TABLE_NAME, connection, if_exists="append", index=False, chunksize=chunksize
        )
        rows = connection.execute(f"SELECT COUNT(*) FROM {TABLE_NAME}").fetchone()[0]

    logger.info(
        "Loaded %s rows into %s (%.1f MB)",
        f"{rows:,}",
        path,
        path.stat().st_size / 1024 / 1024,
    )
    return path


# ------------------------------------------------------------------- querying


def _read_only_connection(db_path: Path) -> sqlite3.Connection:
    """Open the database read-only so a query can never mutate it."""
    return sqlite3.connect(f"file:{db_path.as_posix()}?mode=ro", uri=True)


def run_query(sql: str, db_path: Path | None = None) -> QueryResult:
    """Validate a statement then execute it, returning rows or a clear error."""
    path = Path(db_path or DB_PATH)
    cleaned = (sql or "").strip().rstrip(";").strip()

    safety = check_sql_safety(cleaned)
    if not safety:
        logger.warning("Rejected unsafe SQL: %s", safety.reason)
        return QueryResult(ok=False, sql=cleaned, error=f"Rejected: {safety.reason}")

    if not path.is_file():
        return QueryResult(
            ok=False,
            sql=cleaned,
            error=(
                f"Database not found at {path}. Build it with "
                "'python -m src.talk_to_data.query_runner --rebuild'."
            ),
        )

    # The statement is a validated SELECT, so it is safe to wrap for a row cap.
    capped = f"SELECT * FROM (\n{cleaned}\n) LIMIT {MAX_RESULT_ROWS + 1}"
    try:
        with _read_only_connection(path) as connection:
            frame = pd.read_sql_query(capped, connection)
    except Exception as error:
        logger.warning("Query failed: %s", error)
        return QueryResult(ok=False, sql=cleaned, error=f"Query failed: {error}")

    truncated = len(frame) > MAX_RESULT_ROWS
    if truncated:
        frame = frame.head(MAX_RESULT_ROWS)

    return QueryResult(
        ok=True,
        sql=cleaned,
        dataframe=frame,
        row_count=len(frame),
        truncated=truncated,
    )


def normalise_whitespace(text: str) -> str:
    """Replace exotic spaces LLMs emit inside numbers with plain spaces.

    Narrow and non-breaking spaces are unprintable on a cp1252 Windows console
    and serve no purpose downstream.
    """
    for character in ("\u202f", "\u00a0", "\u2009", "\u2007"):
        text = text.replace(character, " ")
    return text


def summarize_results(
    question: str, results_df: pd.DataFrame | None, error: str | None = None
) -> str:
    """Ask the LLM for a short answer grounded strictly in the returned rows."""
    if error:
        user_prompt = build_summary_user_prompt(question, "", 0, error=error)
    elif results_df is None or results_df.empty:
        user_prompt = build_summary_user_prompt(question, "", 0)
    else:
        preview = results_df.head(SUMMARY_ROW_LIMIT).to_csv(index=False)
        user_prompt = build_summary_user_prompt(question, preview, len(results_df))

    return normalise_whitespace(
        complete(SUMMARY_SYSTEM_PROMPT, user_prompt, max_tokens=300)
    )


def answer_question(question: str, db_path: Path | None = None) -> Answer:
    """Generate SQL, run it, and summarise the result in one call."""
    outcome = Answer(question=question)
    try:
        outcome.sql = nl_to_sql(question)
    except Exception as error:
        outcome.errors.append(f"SQL generation failed: {error}")
        outcome.answer = f"Could not generate SQL for this question: {error}"
        return outcome

    outcome.result = run_query(outcome.sql, db_path=db_path)
    if not outcome.result.ok:
        outcome.errors.append(outcome.result.error)

    outcome.answer = summarize_results(
        question,
        outcome.result.dataframe,
        error=None if outcome.result.ok else outcome.result.error,
    )
    return outcome


def main() -> None:
    # The Windows console defaults to cp1252 and cannot print model output verbatim.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--rebuild", action="store_true", help="rebuild schema and database")
    parser.add_argument("--ask", metavar="QUESTION", help="ask a question end to end")
    parser.add_argument("--sql", metavar="SQL", help="run a SQL statement directly")
    args = parser.parse_args()

    if args.rebuild:
        build_database()
    if args.sql:
        result = run_query(args.sql)
        print(result.error if not result.ok else result.dataframe.to_string(index=False))
    if args.ask:
        outcome = answer_question(args.ask)
        print(f"\nSQL:\n{outcome.sql}\n")
        if outcome.result and outcome.result.ok:
            print(outcome.result.dataframe.to_string(index=False))
        else:
            print(f"ERROR: {'; '.join(outcome.errors)}")
        print(f"\nAnswer: {outcome.answer}")
    if not (args.rebuild or args.ask or args.sql):
        parser.print_help()


if __name__ == "__main__":
    main()
