-- Generated by src/talk_to_data/query_runner.py (--rebuild).
-- One denormalised row per loan applicant, mirroring the master dataset
-- plus derived helper columns and the trained model's score.

DROP TABLE IF EXISTS applicants;

CREATE TABLE applicants (
    SK_ID_CURR INTEGER PRIMARY KEY,       -- INTEGER. Unique applicant id (primary key).
    TARGET INTEGER,                       -- INTEGER. 1 = the applicant defaulted, 0 = repaid. Overall default rate is about 8%.
    NAME_CONTRACT_TYPE TEXT,              -- TEXT. 'Cash loans' or 'Revolving loans'.
    CODE_GENDER TEXT,                     -- TEXT. 'M', 'F', or 'XNA'.
    FLAG_OWN_CAR TEXT,                    -- TEXT. 'Y' or 'N'.
    FLAG_OWN_REALTY TEXT,                 -- TEXT. 'Y' or 'N'.
    CNT_CHILDREN INTEGER,                 -- INTEGER. Number of children.
    AMT_INCOME_TOTAL REAL,                -- REAL. Declared annual income.
    AMT_CREDIT REAL,                      -- REAL. Credit amount of the loan applied for.
    AMT_ANNUITY REAL,                     -- REAL. Loan annuity (annual repayment amount).
    AMT_GOODS_PRICE REAL,                 -- REAL. Price of the goods the loan is financing.
    NAME_TYPE_SUITE TEXT,
    NAME_INCOME_TYPE TEXT,                -- TEXT. e.g. 'Working', 'Commercial associate', 'Pensioner', 'State servant'.
    NAME_EDUCATION_TYPE TEXT,             -- TEXT. One of 'Lower secondary', 'Secondary / secondary special', 'Incomplete higher', 'Higher education', 'Academic degree'.
    NAME_FAMILY_STATUS TEXT,              -- TEXT. e.g. 'Married', 'Single / not married', 'Civil marriage', 'Separated', 'Widow'.
    NAME_HOUSING_TYPE TEXT,               -- TEXT. e.g. 'House / apartment', 'With parents', 'Rented apartment'.
    REGION_POPULATION_RELATIVE REAL,      -- REAL. Normalised population density of the applicant's region.
    DAYS_BIRTH INTEGER,                   -- INTEGER. Age in days, stored NEGATIVE (-9461 means 25.9 years old). Prefer age_years.
    DAYS_EMPLOYED INTEGER,                -- INTEGER. Employment length in days, NEGATIVE. The value 365243 is a placeholder, not real. Prefer years_employed.
    DAYS_REGISTRATION REAL,               -- REAL. Days since registration was changed, NEGATIVE.
    DAYS_ID_PUBLISH INTEGER,              -- INTEGER. Days since the identity document was issued, NEGATIVE.
    OWN_CAR_AGE REAL,
    FLAG_MOBIL INTEGER,
    FLAG_EMP_PHONE INTEGER,
    FLAG_WORK_PHONE INTEGER,
    FLAG_CONT_MOBILE INTEGER,
    FLAG_PHONE INTEGER,
    FLAG_EMAIL INTEGER,
    OCCUPATION_TYPE TEXT,                 -- TEXT. Occupation group, e.g. 'Laborers', 'Core staff', 'Managers'. Often NULL.
    CNT_FAM_MEMBERS REAL,                 -- REAL. Household size.
    REGION_RATING_CLIENT INTEGER,         -- INTEGER. Internal region risk rating, 1 to 3 (3 is worst).
    REGION_RATING_CLIENT_W_CITY INTEGER,
    WEEKDAY_APPR_PROCESS_START TEXT,
    HOUR_APPR_PROCESS_START INTEGER,
    REG_REGION_NOT_LIVE_REGION INTEGER,
    REG_REGION_NOT_WORK_REGION INTEGER,
    LIVE_REGION_NOT_WORK_REGION INTEGER,
    REG_CITY_NOT_LIVE_CITY INTEGER,
    REG_CITY_NOT_WORK_CITY INTEGER,
    LIVE_CITY_NOT_WORK_CITY INTEGER,
    ORGANIZATION_TYPE TEXT,               -- TEXT. Employer industry.
    EXT_SOURCE_1 REAL,                    -- REAL. External credit bureau score 1, 0 to 1. Higher is safer. Often NULL.
    EXT_SOURCE_2 REAL,                    -- REAL. External credit bureau score 2, 0 to 1. Higher is safer.
    EXT_SOURCE_3 REAL,                    -- REAL. External credit bureau score 3, 0 to 1. Higher is safer.
    APARTMENTS_AVG REAL,
    BASEMENTAREA_AVG REAL,
    YEARS_BEGINEXPLUATATION_AVG REAL,
    YEARS_BUILD_AVG REAL,
    COMMONAREA_AVG REAL,
    ELEVATORS_AVG REAL,
    ENTRANCES_AVG REAL,
    FLOORSMAX_AVG REAL,
    FLOORSMIN_AVG REAL,
    LANDAREA_AVG REAL,
    LIVINGAPARTMENTS_AVG REAL,
    LIVINGAREA_AVG REAL,
    NONLIVINGAPARTMENTS_AVG REAL,
    NONLIVINGAREA_AVG REAL,
    APARTMENTS_MODE REAL,
    BASEMENTAREA_MODE REAL,
    YEARS_BEGINEXPLUATATION_MODE REAL,
    YEARS_BUILD_MODE REAL,
    COMMONAREA_MODE REAL,
    ELEVATORS_MODE REAL,
    ENTRANCES_MODE REAL,
    FLOORSMAX_MODE REAL,
    FLOORSMIN_MODE REAL,
    LANDAREA_MODE REAL,
    LIVINGAPARTMENTS_MODE REAL,
    LIVINGAREA_MODE REAL,
    NONLIVINGAPARTMENTS_MODE REAL,
    NONLIVINGAREA_MODE REAL,
    APARTMENTS_MEDI REAL,
    BASEMENTAREA_MEDI REAL,
    YEARS_BEGINEXPLUATATION_MEDI REAL,
    YEARS_BUILD_MEDI REAL,
    COMMONAREA_MEDI REAL,
    ELEVATORS_MEDI REAL,
    ENTRANCES_MEDI REAL,
    FLOORSMAX_MEDI REAL,
    FLOORSMIN_MEDI REAL,
    LANDAREA_MEDI REAL,
    LIVINGAPARTMENTS_MEDI REAL,
    LIVINGAREA_MEDI REAL,
    NONLIVINGAPARTMENTS_MEDI REAL,
    NONLIVINGAREA_MEDI REAL,
    FONDKAPREMONT_MODE TEXT,
    HOUSETYPE_MODE TEXT,
    TOTALAREA_MODE REAL,
    WALLSMATERIAL_MODE TEXT,
    EMERGENCYSTATE_MODE TEXT,
    OBS_30_CNT_SOCIAL_CIRCLE REAL,
    DEF_30_CNT_SOCIAL_CIRCLE REAL,
    OBS_60_CNT_SOCIAL_CIRCLE REAL,
    DEF_60_CNT_SOCIAL_CIRCLE REAL,
    DAYS_LAST_PHONE_CHANGE REAL,          -- REAL. Days since the phone number changed, NEGATIVE.
    FLAG_DOCUMENT_2 INTEGER,
    FLAG_DOCUMENT_3 INTEGER,
    FLAG_DOCUMENT_4 INTEGER,
    FLAG_DOCUMENT_5 INTEGER,
    FLAG_DOCUMENT_6 INTEGER,
    FLAG_DOCUMENT_7 INTEGER,
    FLAG_DOCUMENT_8 INTEGER,
    FLAG_DOCUMENT_9 INTEGER,
    FLAG_DOCUMENT_10 INTEGER,
    FLAG_DOCUMENT_11 INTEGER,
    FLAG_DOCUMENT_12 INTEGER,
    FLAG_DOCUMENT_13 INTEGER,
    FLAG_DOCUMENT_14 INTEGER,
    FLAG_DOCUMENT_15 INTEGER,
    FLAG_DOCUMENT_16 INTEGER,
    FLAG_DOCUMENT_17 INTEGER,
    FLAG_DOCUMENT_18 INTEGER,
    FLAG_DOCUMENT_19 INTEGER,
    FLAG_DOCUMENT_20 INTEGER,
    FLAG_DOCUMENT_21 INTEGER,
    AMT_REQ_CREDIT_BUREAU_HOUR REAL,
    AMT_REQ_CREDIT_BUREAU_DAY REAL,
    AMT_REQ_CREDIT_BUREAU_WEEK REAL,
    AMT_REQ_CREDIT_BUREAU_MON REAL,
    AMT_REQ_CREDIT_BUREAU_QRT REAL,
    AMT_REQ_CREDIT_BUREAU_YEAR REAL,
    bureau_loan_count INTEGER,            -- INTEGER. Number of prior loans on file at the credit bureau. 0 if none.
    bureau_avg_credit_sum REAL,           -- REAL. Average credit amount of those bureau loans. NULL if no bureau history.
    bureau_overdue_count INTEGER,         -- INTEGER. Number of prior bureau loans currently overdue. 0 if none.
    previous_application_count INTEGER,   -- INTEGER. Number of previous applications to this lender. 0 if none.
    previous_avg_amount REAL,             -- REAL. Average amount of those previous applications. NULL if none.
    previous_approval_rate REAL,          -- REAL. Share of previous applications approved, 0 to 1. NULL if none.
    age_years REAL,                       -- REAL. Applicant age in years (already converted from DAYS_BIRTH).
    age_bracket TEXT,                     -- TEXT. Age band: '20-29', '30-39', '40-49', '50-59', '60+'.
    is_retiree_placeholder INTEGER,       -- INTEGER. 1 when DAYS_EMPLOYED held the 365243 placeholder (typically retired).
    years_employed REAL,                  -- REAL. Years in current job. NULL for applicants with no employment record.
    credit_to_income REAL,                -- REAL. AMT_CREDIT divided by AMT_INCOME_TOTAL.
    annuity_to_income REAL,               -- REAL. AMT_ANNUITY divided by AMT_INCOME_TOTAL.
    income_quartile TEXT,                 -- TEXT. Income quartile: 'Q1 (lowest)', 'Q2', 'Q3', 'Q4 (highest)'.
    default_probability REAL,             -- REAL. Probability of default predicted by the LightGBM model, 0 to 1.
    risk_band TEXT                        -- TEXT. Model risk band: 'Low' (<0.3), 'Medium' (0.3-0.6), 'High' (>=0.6).
);

CREATE INDEX idx_applicants_target ON applicants(TARGET);
CREATE INDEX idx_applicants_risk_band ON applicants(risk_band);
CREATE INDEX idx_applicants_name_education_type ON applicants(NAME_EDUCATION_TYPE);
CREATE INDEX idx_applicants_age_bracket ON applicants(age_bracket);
CREATE INDEX idx_applicants_name_income_type ON applicants(NAME_INCOME_TYPE);
